server:
  port: 8000
  tomcat:
    uri-encoding: utf-8

# Database
jdbc:
  driveClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
  username: gavin
  password: 123456

# redis
spring:
  redis:
    database: 2
      host: localhost
      port: 3306
      index: 2
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

